### ISSUE TITLE
Layer Workflow with MDK Middleware not working

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/NXP_FRDM-MCXN947_BSP#2]
The board layer should select a core with `device:`.

```yml
layer:
  type: Board
  description: Board setup for Arduino shield
  for-board: NXP::FRDM-MCXN947
  for-device: NXP::MCXN947VDF:cm33_core0
  device: :cm33_core0
```

This is also missing in the documentation
https://open-cmsis-pack.github.io/cmsis-toolbox/YML-Input-Format/#layer

The guidelines for multi-core devices need to be clearified.
